development:
  adapter: postgresql
  encoding: unicode
  database: nytech_development
  pool: 5
  username: nytech
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: nytech_test
  pool: 5
  username: nytech
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: nytech_production
  pool: 5
  username: nytech
  password:
